#!/bin/bash

if command -v firefox >/dev/null 2>&1; then
    firefox ./docs/index.html &
elif command -v chromium >/dev/null 2>&1; then
    chromium ./docs/index.html &
else
    echo "Neither Firefox nor Chromium is installed."
    exit 1
fi